default:
  APPLICATION_URL_DRS: $APPLICATION_URL/esbdrs/registration
  TEMPLATE_PATH: ../templates
  TOB_API_URL: https://devex-von-test.pathfinder.gov.bc.ca/api
  TOB_APP_URL: https://devex-von-test.pathfinder.gov.bc.ca
  WALLET_SEED_BCESB: bc_esb_drs_dev_00000000000000000
  #INDY_GENESIS_URL: https://raw.githubusercontent.com/sovrin-foundation/sovrin/1.1.50-master/sovrin/pool_transactions_sandbox_genesis
  #LEDGER_PROTOCOL_VERSION: "1.3"
  #AUTO_REGISTER_DID: 0
