version: '3'
services:

  caddy2:
    build:
      context: ../esbdrs-x
      dockerfile: Dockerfile.caddy
    environment:
      TOB_API_URL: ${TOB_API_URL:-}
      WEB_BASE_HREF: ${WEB_BASE_HREF:-/}
      WEB_HOST_NAME: ${WEB_HOST_NAME:-0.0.0.0}
      WEB_HOST_PORT: ${WEB_HOST_PORT:-8080}
      WEB_HOST_TLS: ${WEB_HOST_TLS:-off}
      AGENT_HOST: ${AGENT_HOST:-agent}
      AGENT_PORT: ${AGENT_PORT:-8000}
      AGENT_USER: ${AGENT_USER:-test}
      AGENT_PASSWORD: ${AGENT_PASSWORD:-test}
    links:
      - esbdrs-agent:agent
    networks:
      - vonx
    ports:
      - ${WEB_HTTP_PORT:-5000}:${WEB_HOST_PORT:-8080}
    volumes:
      - caddy2-data:/root/.caddy
      - caddy2-logs:/srv/logs

  esbdrs-agent:
    build:
      context: ../esbdrs-x
      dockerfile: Dockerfile
    environment:
      APPLICATION_URL: ${APPLICATION_URL:-http://localhost:5000}
      CONFIG_ROOT: ../config
      ENVIRONMENT: ${ENVIRONMENT:-default}
      ENABLE_GUNICORN: ${ENABLE_GUNICORN:-0}
      INDY_LEDGER_URL: ${LEDGER_URL:-http://localhost:9000}
      FORMS: ${FORMS:-}
      ISSUERS: ${ISSUERS:-}
      LOG_LEVEL: ${LOG_LEVEL:-}
      PYTHON_ENV: ${PYTHON_ENV:-development}
      TOB_API_URL: ${TOB_API_URL:-}
      TOB_APP_URL: ${TOB_APP_URL:-}
      WALLET_TYPE: ${WALLET_TYPE}
      POSTGRESQL_WALLET_HOST: ${POSTGRESQL_WALLET_HOST}
      POSTGRESQL_WALLET_PORT: ${POSTGRESQL_WALLET_PORT}
      POSTGRESQL_WALLET_USER: ${POSTGRESQL_USER}
      POSTGRESQL_WALLET_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_WALLET_ADMIN_PASSWORD: ${POSTGRESQL_ADMIN_PASSWORD}
      WALLET_ENCRYPTION_KEY: ${WALLET_ENCRYPTION_KEY}
      WALLET_SEED_BCESB: ${WALLET_SEED_BCESB:-}
      ISSUER_WALLET_DID: ${ISSUER_WALLET_DID}
      HTTP_FORCE_CLOSE_CONNECTIONS: "true"
    external_links:
       - tob_tob-api_1:tob-api
    networks:
      - orgbook
      - vonx
    depends_on:
      - esbdrs-wallet-db
    entrypoint: >
      /bin/bash -c "
        echo sleeping ...;
        sleep 5;
        ../docker-entrypoint.sh;"
    volumes:
      - esbdrs-agent-wallet:/home/indy/.indy_client/wallet

  esbdrs-wallet-db:
    image: registry.access.redhat.com/rhscl/postgresql-95-rhel7:9.5
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
    networks:
      - orgbook
    ports:
      - 5435:5432
    volumes:
      - esbdrs-wallet-db:/var/lib/pgsql/data

volumes:
  caddy2-data:
  caddy2-logs:
  esbdrs-agent-wallet:
  esbdrs-wallet-db:

networks:
  vonx:
  orgbook:
    external:
      name: tob_tob


